spring.application.name=EmployeePayrollManagement
server.port=8081

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/myDb         # the address of my datasource
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver      #driver that we will use to interact with db

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update                 # the old db will be updated
spring.jpa.show-sql=true                   # query in terminal
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect           # type of db used in hibernate so that uske lang mai transalte

rootLogger.level =INFO

appender.console.type = Console
appender.console,name = Fahmid
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

rootLogger.appenderRef.stdout.ref=Fahmid